In [2]:
import numpy as np
import pandas as pd

#### Dataframe

##### The main data structure we use in Pandas, is called a DataFrame - it's basically a table.

In [3]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [7]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               5 non-null      str
 1   Model              5 non-null      str
 2   Year               5 non-null      int64
 3   Engine HP          4 non-null      float64
 4   Engine Cylinders   5 non-null      int64
 5   Transmission Type  5 non-null      str
 6   Vehicle_Style      5 non-null      str
 7   MSRP               5 non-null      int64
dtypes: float64(1), int64(3), str(4)
memory usage: 452.0 bytes

In [14]:
df.head(n=1)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000

In [15]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [19]:
df["Engine HP"]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [30]:
df[['Make', 'Model', 'Year', 'Transmission Type','Engine HP']]

      Make     Model  Year Transmission Type  Engine HP
0   Nissan    Stanza  1991            MANUAL      138.0
1  Hyundai    Sonata  2017         AUTOMATIC        NaN
2    Lotus     Elise  2010            MANUAL      218.0
3      GMC    Acadia  2017         AUTOMATIC      194.0
4   Nissan  Frontier  2017            MANUAL      261.0

In [31]:
df['id'] = [1,2,3,4,5]

In [32]:
df.id

0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

In [33]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [38]:
del df['id']

In [39]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

#### Index

In [40]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [46]:
df.loc[3]

Make                       GMC
Model                   Acadia
Year                      2017
Engine HP                194.0
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style          4dr SUV
MSRP                     34450
Name: 3, dtype: object

In [48]:
df.index = ['a', 'b','c','d','e']

In [49]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [52]:
df.iloc[[0,2,4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [59]:
df.reset_index(drop=True)

,level_0,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,0,a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,1,b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,2,c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,3,d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,4,e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [60]:
df = df.reset_index(drop=True)
df

,level_0,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,0,a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,1,b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,2,c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,3,d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,4,e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340